## Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [21]:
import numpy as np

In [66]:
a = np.array([1, 2, 3, 4, 5])
n = 3
b = np.column_stack([a**(n-i-1) for i in range(n)])
print(b)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [68]:
a = np.array([1, 2, 3, 4, 5])
n = 3
c = np.vander(a, n)
print(c)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [69]:
a = np.array([1, 2, 3, 4, 5])
n = 3
d = np.vander(a, n, increasing = True)
print(d)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
